config/routes.rb
Rails.application.routes.draw do

  root :to => 'seminars#index'

  get 'participants/future-faculty-program', to: 'participants/programs/future_faculty#index',
      format: 'xlsx', as: 'future_faculty_program_participants'

  resources :participants, except: :new, controller: "participants/base" do
    resource 'future-faculty-program',
             as: :future_faculty_program,
             controller: "participants/programs/future_faculty",
             only: [:enroll, :unenroll,
                    :graduate, :ungraduate,
                    :drop, :undrop, :reenroll] do
      member do
        patch 'enroll'
        patch 'unenroll'
        patch 'graduate'
        patch 'ungraduate'
        patch 'drop'
        patch 'undrop'
        patch 'reenroll'
      end
    end
    
    resource 'transcript', only: :show, controller: "participants/transcripts", format: 'pdf'

    scope shallow_prefix: "participant" do
      resources 'activities',
                only: [:edit, :create, :update, :destroy],
                controller: "participants/activities",
                shallow: true
     end
  end
  

  get 'transcript', to: 'participants/transcripts#show', format: 'pdf'

  patch 'admin/seminars/update_seminar' => 'admin/seminars#update_seminar', :as => 'update_whole_seminar'

  resources :seminars do
    resources :registrations, only: [:create, :destroy]
  end
  get 'registrations', to: 'registrations#index', :as => 'registrations'
  patch 'admin/seminars/mark_all_attended' => 'admin/seminars#mark_all_attended', :as => 'mark_all_attended_seminar'
  patch 'admin/seminars/mark_all_cleared' => 'admin/seminars#mark_all_cleared', :as => 'mark_all_cleared_seminar'
  
  patch 'admin/seminars/mark_attended' => 'admin/seminars#mark_attended', :as => 'mark_attended_seminar'
  

  resources :sessions, only: [:create, :destroy]
  get 'login',  to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', via: [:get, :delete]

  resource :search, only: :show

  get 'admin' => 'admin/seminars#index', :as => 'root_admin_url'
  namespace :admin do
    resources :seminars do
      resources :registrations
    end

    resources :spreadsheets, only: [:show]
    resources :settings, only: [:index, :update]
  end
  

end

app/models/future_faculty.rb
module FutureFaculty
  def self.table_name_prefix
    'future_faculty_'
  end
end

app/models/program.rb
module Program
  def self.table_name_prefix
    'program_'
  end
end

app/models/program/progress_status_type.rb
class Program::ProgressStatusType < ActiveRecord::Base
  include ::Typable
end

app/models/programs.rb
module Programs
  def self.table_name_prefix
    ''
  end
end

app/models/programs/future_faculty.rb
module Programs::FutureFaculty
  def self.table_name_prefix
    'future_faculty_'
  end
end

app/models/programs/future_faculty/enrollment.rb
class Programs::FutureFaculty::Enrollment

  def initialize( participant )
    # TODO: remove hardcoded key
    version = Programs::FutureFaculty::RequirementsVersion.find_by_key '2015'

    # TODO: probably should be a save trigger
    status = Program::ProgressStatusType.find 'incomplete'

    participant.future_faculty_progress_status = status
    participant.future_faculty_enrollment = version
    
    participant.save!
  end

  def self.destroy( participant )
    # TODO: remove hardcoded key
    version = Programs::FutureFaculty::RequirementsVersion.find_by_key '2015'
    participant.activities.program_requirements(:future_faculty).destroy_all
    participant.future_faculty_enrollment = nil
    participant.future_faculty_progress_status = nil
    participant.save!
  end

  def self.find( participant )
    participant.future_faculty_enrollment
  end

end

app/models/programs/future_faculty/requirement.rb
class Programs::FutureFaculty::Requirement < ActiveRecord::Base
  belongs_to :requirements_version, class_name: 'Programs::FutureFaculty::RequirementsVersion', foreign_key: :future_faculty_requirements_version_id
  belongs_to :requirement_category, class_name: 'Programs::FutureFaculty::RequirementCategory', foreign_key: :future_faculty_requirement_category_id

  has_many :activities, class_name: 'Participant::Activity'

  validates_uniqueness_of :key, scope: :requirements_version, message: "exists for this requirements version"
  validates_presence_of :key, :label, :activity_class, :requirement_category, :requirements_version, message: "required"
  validates_associated :requirement_category, :requirements_version
end

app/models/programs/future_faculty/requirement_category.rb
class Programs::FutureFaculty::RequirementCategory < ActiveRecord::Base
end

app/models/programs/future_faculty/requirements_version.rb
class Programs::FutureFaculty::RequirementsVersion < ActiveRecord::Base
  has_many :requirements, class_name: 'Programs::FutureFaculty::Requirement',
           foreign_key: :future_faculty_requirements_version_id

  has_many :categories, -> { distinct }, through: :requirements, source: :requirement_category
  
  has_many :participants, foreign_key: :future_faculty_enrollment_id

  has_many :pending_graduates, -> { ffp_participants('complete') },
           class_name: 'Participant', foreign_key: :future_faculty_enrollment_id


  def calculate_participant_status( participant )

    # Participant must be enrolled in an ffp version to have a status
    unless participant.future_faculty_enrollment
      participant.future_faculty_progress_status = nil
      return
    end

    # Do not recalculate terminal states
    if participant.future_faculty_progress_status == Program::ProgressStatusType.find('dropout') ||
       participant.future_faculty_progress_status == Program::ProgressStatusType.find('graduated')
      return
    end

    # Calculate various requirements of the programs
    participant.future_faculty_progress_status =
      case participant.future_faculty_enrollment.key
      when "2015"
        if ( participant.attended_seminars.size >= 8 ) &&
           ( participant.attended_seminars.with_tag("core").size >= 4 ) &&
           ( ( participant.activities.where('completed_on is not null and type="Participant::Activities::TeachingObservation"').size >= 2 ) ||
             ( participant.activities.where('completed_on is not null and type="Participant::Activities::TeachingObservation"').size >= 1 &&
               participant.activities.where('completed_on is not null and type="Participant::Activities::EarlyCourseFeedback"').size >= 1 ) ||
             ( participant.activities.where('completed_on is not null and type="Participant::Activities::TeachingObservation"').size >= 1 &&
               participant.activities.where('completed_on is not null and type="Participant::Activities::MicroteachingWorkshop"').size >= 1 )
           ) &&
           ( participant.activities.where('completed_on is not null and type="Participant::Activities::CourseAndSyllabusDesignProject"').size >= 1 ) &&
           ( participant.activities.where('completed_on is not null and type="Participant::Activities::TeachingStatementProject"').size >= 1 )
          Program::ProgressStatusType.find('complete')
        else
          Program::ProgressStatusType.find('incomplete')
        end # 2015
      when "2012"
        if ( participant.attended_seminars.size >= 8 ) &&
           ( participant.attended_seminars.with_tag("core").size >= 4 ) &&
           ( ( participant.activities.where('completed_on is not null and type="Participant::Activities::ClassroomObservation"').size >= 2 ) ||
             ( participant.activities.where('completed_on is not null and type="Participant::Activities::ClassroomObservation"').size >= 1 &&
               participant.activities.where('completed_on is not null and type="Participant::Activities::MicroteachingObservation"').size >= 1 )
           ) &&
           ( participant.activities.where('completed_on is not null and type="Participant::Activities::CourseAndSyllabusDesignProject"').size >= 1 ) &&
           ( participant.activities.where('completed_on is not null and type="Participant::Activities::IndividualProject"').size >= 1 )
          Program::ProgressStatusType.find('complete')
        else
          Program::ProgressStatusType.find('incomplete')
        end # 2012
      else
        nil
      end # case
  end # calculate_participant_status


end

app/controllers/participants/programs/future_faculty_controller.rb
class Participants::Programs::FutureFacultyController < ApplicationController

  def index
    respond_to do |format|
      format.xlsx do
        @participants = Participant.all
        response.headers['Content-Disposition'] = 'attachment; filename="FutureFacultyParticipants.xlsx"'
      end
    end
  end

  def enroll
    @participant = Participant.find( params[:participant_id] )
    Programs::FutureFaculty::Enrollment.new( @participant )

    respond_to do |format|
      format.js
    end
  end

  def unenroll
    @participant = Participant.find( params[:participant_id] )
    Programs::FutureFaculty::Enrollment.destroy( @participant )

    respond_to do |format|
      format.js
    end
  end

  def graduate
    @participant = Participant.find( params[:participant_id] )

    unless Programs::FutureFaculty::Enrollment.find( @participant ).nil?
      @participant.future_faculty_progress_status_id = 3
      @participant.future_faculty_program_graduated_on = Date.today
      @participant.save
    end

    redirect_to @participant
  end

  def ungraduate
    @participant = Participant.find( params[:participant_id] )

    unless Programs::FutureFaculty::Enrollment.find( @participant ).nil?
      @participant.future_faculty_progress_status_id = 2
      @participant.save
    end

    respond_to do |format|
      format.js
    end
  end

  def drop
    @participant = Participant.find( params[:participant_id] )
    unless Programs::FutureFaculty::Enrollment.find( @participant ).nil?
      @participant.future_faculty_progress_status_id = 4
      @participant.save
    end
    redirect_to @participant
  end

  def undrop
    @participant = Participant.find( params[:participant_id] )
    unless Programs::FutureFaculty::Enrollment.find( @participant ).nil?
      @participant.future_faculty_progress_status_id = 1
      @participant.save
    end

    respond_to do |format|
      format.js
    end
  end

  def reenroll
    @participant = Participant.find( params[:participant_id] )
    unless Programs::FutureFaculty::Enrollment.find( @participant ).nil?
      @participant.future_faculty_progress_status_id = 1
      @participant.save
    end
    redirect_to @participant
  end


end

app/helpers/participants/programs/future_faculty_helper.rb
module Participants::Programs::FutureFacultyHelper
end

app/helpers/participants/programs_helper.rb
module Participants::ProgramsHelper

  def hide_if_unenrolled( participant, program )
    "display: none;" unless "Programs::#{program.to_s.classify}::Enrollment".constantize.find(participant)
  end
  
end

app/views/participants/programs/future_faculty/_participant_graduation.html.erb
<% if not Programs::FutureFaculty::Enrollment.find( @participant ).nil? %>
    <% if @participant.future_faculty_progress_status_id == 2 %>

        <%= link_to( "Graduate from Future Faculty",
                    graduate_participant_future_faculty_program_url( @participant ),
                    data: { confirm: "Are you sure?" },
                    class: ['boxy', 'hide-if-enrolled-in-future-faculty'],
                    method: :patch ) %>
    <% elsif @participant.future_faculty_progress_status_id == 1 %>
        <%= link_to( "Drop from Future Faculty",
                    drop_participant_future_faculty_program_url( @participant ),
                    data: { confirm: "Are you sure?" },
                    class: ['boxy', 'hide-if-enrolled-in-future-faculty'],
                    method: :patch ) %>
        <%= link_to( "Force-Graduate from Future Faculty",
                    graduate_participant_future_faculty_program_url( @participant ),
                    data: { confirm: "Are you sure?" },
                    class: ['boxy', 'hide-if-enrolled-in-future-faculty'],
                    method: :patch ) %>
    <% elsif @participant.future_faculty_progress_status_id == 4 %>
        <%= link_to( "Re-Enroll into Future Faculty",
                    reenroll_participant_future_faculty_program_url( @participant ),
                    data: { confirm: "Are you sure?" },
                    class: ['boxy', 'hide-if-enrolled-in-future-faculty'],
                    method: :patch ) %>
    <% end %>
<% end %>

app/views/participants/programs/future_faculty/_participant_information_links.html.erb
<div style="width: 100%; margin-bottom: 20px;">
Future Faculty Program Status:
<% if not Programs::FutureFaculty::Enrollment.find( @participant ).nil? %>
    <%= @participant.future_faculty_progress_status.label %>
    <% if @participant.future_faculty_progress_status_id == 3 %>
        <br/>Completion Date (click to edit): <%= best_in_place @participant, :future_faculty_program_graduated_on, :as => :date, :place_holder => "N/A" %>
    <% end %>
<% else %>
    Not enrolled
<% end %>
</div>

<% if Programs::FutureFaculty::Enrollment.find( @participant ).nil? %>

  <%= link_to( "Enroll in Future Faculty",
               enroll_participant_future_faculty_program_url( @participant ),
               remote: true,
               class: ['boxy', 'hide-if-enrolled-in-future-faculty'],
               method: :patch ) %>

<% end %>

app/views/participants/programs/future_faculty/_participant_progress.html.erb
<section id="future-faculty">

    <%= render( 'participants/programs/future_faculty/participant_requirements_form', participant: participant ) %>

</section>

app/views/participants/programs/future_faculty/_participant_requirements_form.html.erb
<% if Programs::FutureFaculty::Enrollment.find( @participant ).nil?  %>
    <% category_requirements = Programs::FutureFaculty::RequirementsVersion.last.requirements.group_by(&:requirement_category) %>
    <% ffp_categories = Programs::FutureFaculty::RequirementsVersion.last.categories %>
<% else %>
    <% category_requirements = @participant.future_faculty_enrollment.requirements.group_by(&:requirement_category) %>
    <% ffp_categories = @participant.future_faculty_enrollment.categories %>
<% end %>

<% ffp_categories.each do |c| %>
<div class="panel panel-default">

  <div class="panel-heading requirement-category-label">
    <h1 class="panel-title"><%= c.label %></h1>
  </div>

  <div class="panel-body">

    <div class="list-group">
      <% category_requirements[c].each do |r| %>
      <%= render( partial: "participants/activities/activity", collection: participant.activities.where(type: r.activity_class ) ) %>
      <%# TODO: None on no activitities for requirements %>
      <%#   raw( "<div class=\"list-group-item\"><h2 class=\"list-group-item-heading\">None.</h2></div>" ) %>
      <% end %>
    </div>

    <%= render( "participants/activities/select_form",
        activity: participant.activities.build, type_options: category_requirements[c] ) %>
    <script>$( ".completed_on" ).datepicker({dateFormat: "yy-mm-dd"});</script>    
  </div>
</div>
<% end %>

app/views/participants/programs/future_faculty/drop.js.erb
$("a.hide-if-enrolled-in-future-faculty").
     addClass( "success" ).
     attr( "href",
           "<%= escape_javascript undrop_participant_future_faculty_program_url @participant %>" ).
     html("Dropped! Undo?").
     delay(10000).
     fadeOut();

app/views/participants/programs/future_faculty/enroll.js.erb
$("a.hide-if-enrolled-in-future-faculty").
    addClass( "success" ).
    attr( "href",
          "<%= escape_javascript unenroll_participant_future_faculty_program_url @participant %>" ).
    html("Enrolled! Undo?").
    delay(10000).
    fadeOut();

$("#future-faculty").html("<%= j render( "participant_requirements_form", participant: @participant ) %>");

<%# TODO: This is a gross copy from base.coffee %>
$(".add-participant-activity-form").hide();

$(".btn-add-participant-activity").click(function (event){
      $(this).toggle();
      $(this).closest(".add-participant-activity-wrapper").find(".add-participant-activity-form").slideDown();
});

$(".list-group-item.activity").find("[data-method=\"delete\"]").click( function(event) {
     $(this).closest(".list-group-item.activity").attr("data-participant-activity","remove");
     });

<%# TODO: Match against activity type instead of a data attr (see: p_a/create.js.erb) %>
$(".add-participant-activity-form").find("[type=\"submit\"]").click(function (event) {
           $(this).closest(".panel-body").find(".list-group").attr("data-participant-activity","add");
});



$(".add-participant-activity-form-section").hide();
$(".add-participant-activity-section").click( function (event){
       id=$(this).attr("id") + "-form";
        $(this).closest(".add-participant-activity-wrapper").find(".add-participant-activity-form").slideDown();
        $(".add-participant-activity-form-section#"+id).slideDown();
        $(this).parent().parent().parent().toggle();
        event.preventDefault();
});



$("#future-faculty").slideDown();

app/views/participants/programs/future_faculty/graduate.js.erb
$("a.hide-if-enrolled-in-future-faculty").
     addClass( "success" ).
     attr( "href",
           "<%= escape_javascript ungraduate_participant_future_faculty_program_url @participant %>" ).
     html("Graduated! Undo?").
     delay(10000).
     fadeOut();

app/views/participants/programs/future_faculty/reenroll.js.erb
$("a.hide-if-enrolled-in-future-faculty").
     addClass( "success" ).
     attr( "href",
           "<%= escape_javascript reenroll_participant_future_faculty_program_url @participant %>" ).
     html("Re-Enrolled! Undo?").
     delay(10000).
     fadeOut();

app/views/participants/programs/future_faculty/unenroll.js.erb
$("a.hide-if-enrolled-in-future-faculty").
    clearQueue().
    removeClass( "success" ).
    attr( "href",
          "<%= escape_javascript enroll_participant_future_faculty_program_url @participant %>" ).
    html("Enroll in Future Faculty");

$("#future-faculty").slideUp();