config/routes.rb
Rails.application.routes.draw do

  root :to => 'seminars#index'

  get 'participants/future-faculty-program', to: 'participants/programs/future_faculty#index',
      format: 'xlsx', as: 'future_faculty_program_participants'

  resources :participants, except: :new, controller: "participants/base" do
    resource 'future-faculty-program',
             as: :future_faculty_program,
             controller: "participants/programs/future_faculty",
             only: [:enroll, :unenroll,
                    :graduate, :ungraduate,
                    :drop, :undrop, :reenroll] do
      member do
        patch 'enroll'
        patch 'unenroll'
        patch 'graduate'
        patch 'ungraduate'
        patch 'drop'
        patch 'undrop'
        patch 'reenroll'
      end
    end
    
    resource 'transcript', only: :show, controller: "participants/transcripts", format: 'pdf'

    scope shallow_prefix: "participant" do
      resources 'activities',
                only: [:edit, :create, :update, :destroy],
                controller: "participants/activities",
                shallow: true
     end
  end
  

  get 'transcript', to: 'participants/transcripts#show', format: 'pdf'

  patch 'admin/seminars/update_seminar' => 'admin/seminars#update_seminar', :as => 'update_whole_seminar'

  resources :seminars do
    resources :registrations, only: [:create, :destroy]
  end
  get 'registrations', to: 'registrations#index', :as => 'registrations'
  patch 'admin/seminars/mark_all_attended' => 'admin/seminars#mark_all_attended', :as => 'mark_all_attended_seminar'
  patch 'admin/seminars/mark_all_cleared' => 'admin/seminars#mark_all_cleared', :as => 'mark_all_cleared_seminar'
  
  patch 'admin/seminars/mark_attended' => 'admin/seminars#mark_attended', :as => 'mark_attended_seminar'
  

  resources :sessions, only: [:create, :destroy]
  get 'login',  to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', via: [:get, :delete]

  resource :search, only: :show

  get 'admin' => 'admin/seminars#index', :as => 'root_admin_url'
  namespace :admin do
    resources :seminars do
      resources :registrations
    end

    resources :spreadsheets, only: [:show]
    resources :settings, only: [:index, :update]
  end
  

end

app/models/setting.rb
class Setting < ActiveRecord::Base
#  attr_accessible :label, :key, :value
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  before_action :require_administrator

  def index
    @settings = Setting.all
    @consultants = Participant.where(consultant: true)
    @pending_graduates = Programs::FutureFaculty::RequirementsVersion.find_each.map { |x| x.pending_graduates }.flatten
    @nudges = Participant::Activity.all.where("type='Participant::Activities::MicroteachingWorkshop' or type='Participant::Activities::EarlyCourseFeedback' or type='Participant::Activities::TeachingObservation'").where("memo_completed_on is null").where("completed_on < ?",3.weeks.ago).order(:completed_on)
  end

  def update
    setting = Setting.find params[:id]
    setting.update_attributes setting_params
    setting.save
    redirect_to action: 'index'
  end

  private
  def setting_params
    if current_user.is_admin?
      params.require(:setting).permit(:value)
    end
  end

end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/views/admin/settings/_consultants.html.erb
<div class="panel panel-default">

    <div class="panel-heading">
        <div class="row">
            <div class="col-md-12">
        <h1 class="panel-title pull-left">Consultants</h1>

        <%= form_for( Participant.new, url: participants_path, html: { class: "form-inline pull-left" } ) do |f| %>
            <div class="input-group">
                <span class="input-group-btn">
                    <%= f.submit '+', class: "btn btn-default" %>
                </span>
                <%= f.text_field :andrewid, {class: "form-control"} %>
            </div>
            <%= f.hidden_field :consultant, value: true %>

        <% end %>
            </div>
        </div>
    </div>

    <div class="panel-body">

        <table class="table table-striped">
            <% @consultants.each do |c| %>

                <tr>
                    <td><%= c.name %></td>
                    <td><%= c.andrewid %></td>
                    <td>
                        <%= link_to "[x]", participant_path(c,
                                                            :participant => { :consultant => false}),
                                                            :method => :put
                        %>
                    </td>
                </tr>

            <% end %>
            <tr>
                <td colspan="2">

                </td>
            </tr>
        </table>

    </div><!-- panel-body -->
</div><!-- panel -->

app/views/admin/settings/_notifications.html.erb
<div class="panel panel-default">

    <div class="panel-heading notifications">
        <div class="row">
            <div class="col-md-12">
                <h1 class="panel-title pull-left">Notifications</h1>
                <%= link_to raw('<span class="glyphicon glyphicon-lg glyphicon-download-alt"></span><span class="sr-only">Download FFP Spreadsheet</span>'),
                    future_faculty_program_participants_url(:format => :xlsx) %>
            </div>
        </div>
    </div>

    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <h2>Nudge the Consultant!</h2>
                <table class="table table-striped">
                    <% @nudges.each do |a| %>
                        <tr>
                            <td><%= a.observer.name if a.observer %></td>
                            <td><%= link_to( a.participant.name, a.participant ) %></strong><br/> <%= a.future_faculty_requirement ? a.future_faculty_requirement.label : '' %><br/><span style="font-size: 11px"><%= a.completed_on %></span></td>
                                
                            <td><%#= c.andrewid %></td>
                        </tr>
                    <% end %>
                </table>
            </div>

            <div class="col-md-6">
                <h2>Graduate Me!</h2>
                <table class="table table-striped">
                    <% @pending_graduates.each do |g| %>
                        <tr>
                            <td><%= link_to g.name,g %></td>
                            <td><%#= c.andrewid %></td>
                        </tr>
                    <% end %>
                </table>
            </div>

    </div><!-- panel-body -->
</div><!-- panel -->

app/views/admin/settings/_settings.html.erb
<div class="panel panel-default">
    
    <div class="panel-heading">
        <h1 class="panel-title">Application-wide Settings</h1>
    </div>
    
    <div class="panel-body">

        <table class="table table-striped">
            <% @settings.each do |setting| %>
                
                <tr>
                    <td>
                        <%= form_for [:admin, setting] do |f| %>
                            <%= f.label :value, setting.label %>: <%= f.text_field :value %>
                            
                            <%= f.submit "Update setting" %>
                        <% end %>                                    
                    </td>
                </tr>
                
            <% end %>                        
            </table>
            
    </div><!-- panel-body -->
</div><!-- panel -->

app/views/admin/settings/index.html.erb
<section id="settings">
    <%= render "notifications" %>

    <%= render "consultants" %>
    
    <%= render "settings" %>
</section>
    