config/routes.rb
Rails.application.routes.draw do

  root :to => 'seminars#index'

  get 'participants/future-faculty-program', to: 'participants/programs/future_faculty#index',
      format: 'xlsx', as: 'future_faculty_program_participants'

  resources :participants, except: :new, controller: "participants/base" do
    resource 'future-faculty-program',
             as: :future_faculty_program,
             controller: "participants/programs/future_faculty",
             only: [:enroll, :unenroll,
                    :graduate, :ungraduate,
                    :drop, :undrop, :reenroll] do
      member do
        patch 'enroll'
        patch 'unenroll'
        patch 'graduate'
        patch 'ungraduate'
        patch 'drop'
        patch 'undrop'
        patch 'reenroll'
      end
    end
    
    resource 'transcript', only: :show, controller: "participants/transcripts", format: 'pdf'

    scope shallow_prefix: "participant" do
      resources 'activities',
                only: [:edit, :create, :update, :destroy],
                controller: "participants/activities",
                shallow: true
     end
  end
  

  get 'transcript', to: 'participants/transcripts#show', format: 'pdf'

  patch 'admin/seminars/update_seminar' => 'admin/seminars#update_seminar', :as => 'update_whole_seminar'

  resources :seminars do
    resources :registrations, only: [:create, :destroy]
  end
  get 'registrations', to: 'registrations#index', :as => 'registrations'
  patch 'admin/seminars/mark_all_attended' => 'admin/seminars#mark_all_attended', :as => 'mark_all_attended_seminar'
  patch 'admin/seminars/mark_all_cleared' => 'admin/seminars#mark_all_cleared', :as => 'mark_all_cleared_seminar'
  
  patch 'admin/seminars/mark_attended' => 'admin/seminars#mark_attended', :as => 'mark_attended_seminar'
  

  resources :sessions, only: [:create, :destroy]
  get 'login',  to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', via: [:get, :delete]

  resource :search, only: :show

  get 'admin' => 'admin/seminars#index', :as => 'root_admin_url'
  namespace :admin do
    resources :seminars do
      resources :registrations
    end

    resources :spreadsheets, only: [:show]
    resources :settings, only: [:index, :update]
  end
  

end

app/controllers/admin/spreadsheets_controller.rb
class Admin::SpreadsheetsController < ApplicationController
  before_action :require_administrator

  def show
    if params[:id] == 'participants'
      @participants = Participant.all
      render 'participants_spreadsheet'

    elsif params[:id] == 'seminars'
      @display_tag = Setting.find_by_key('admin-list-tag').value
      @seminars = Seminar.all
      render 'seminars_spreadsheet'

    else
      flash[:error] = 'Spreadsheet not found'
      redirect_to root_url

    end
  end

end

app/helpers/admin/spreadsheets_helper.rb
module Admin::SpreadsheetsHelper
end

app/views/admin/spreadsheets/participants_spreadsheet.html.erb
<table id="participants-spreadsheet" class="spreadsheet">

  <thead>
    <tr>
      <th>Name</th>
      <th>Andrew ID</th>
      <th>Department</th>
      <th>Class Level</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |p| %>
    <tr>
      <td><% unless p.name.nil? %><%= link_to p.name, participant_url(p.andrewid) %><% end %></td>
      <td><% unless p.andrewid.nil? %><%= p.andrewid %><% end %></td>
      <td><%= sanitize [p.department].join(',<br/>'), :tags => %w(br) %></td>
      <td><% unless p.student_class.nil? %><%= p.student_class %><% end %></td>
      <td>
	<%= link_to p.registrations.size, '#', :class => 'registrations_popup' %>
	<div class="reg" style="display: none">
	  <% p.registrations.each do |r| %>
	  <%= r.seminar.title %> (<%= r.status %>)<br/>
	  <% end %>
	</div>
      </td>
    </tr>
    <% end %>
  </tbody>

</table>

app/views/admin/spreadsheets/seminars_spreadsheet.html.erb
<table id="seminars-spreadsheet" class="spreadsheet">

  <thead>
    <tr>
      <th>Title</th>
      <th>Start Date</th>
      <th>Status</th>
      <th>Description</th>
      <th>Registrations</th>
      <th># Confirmed</th>
      <th># Pending</th>
      <th>Percent Filled</th>
      <th>Tags</th>
    </tr>
  </thead>

  <tbody>
    <% @seminars.each do |s| %>
    <tr>
      <td><%= s.title %></td>
      <td><%= s.start_at.to_date %></td>
      <td><%= s.status %></td>
      
      <td class="truncate">
	<div class="preview">
	  <%= truncate s.description, :length => 40 %>
	</div>
	<div class="truncated">
	  <%= s.description %>
	  <%= link_to 'hide', '#', :class => 'hide-text' %>
	</div>
      </td>

      <td>
	<%= link_to s.registrations.size, admin_seminar_path( s ) %>
      </td>

      <td>
	<%= s.registrations.confirmed.size %>
      </td>

      <td>
	<%= s.registrations.pending.size %>
      </td>

      <td>
	<%= s.capacity_percentage.to_s %>%
      </td>

      <td>
	<%= s.tags.join(', ') %>
      </td>
    </tr>
    <% end %>
  </tbody>

</table>

<%# TODO: such a hack; see spreadsheets.js.coffee %>
<script type="text/javascript">
  var default_filter="<%= @display_tag %>";
</script>

app/views/admin/spreadsheets/show.html.erb
<table id="participants-spreadsheet" class="spreadsheet">

  <thead>
    <tr>
      <th>Name</th>
      <th>Andrew ID</th>
      <th>Department</th>
      <th>Class Level</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |p| %>
    <tr>
      <td><%= p.name %></td>
      <td><%= p.andrewid %></td>
      <td><%= sanitize [p.department].join(',<br/>'), :tags => %w(br) %></td>
      <td><%= p.student_class %></td>
      <td>
	<%= link_to p.registrations.size, '#' %>
	<div class="reg" style="display: none">
	  <% p.registrations.each do |r| %>
	  <%= r.seminar.title %> (<%= r.status %>)<br/>
	  <% end %>
	</div>
      </td>
    </tr>
    <% end %>
  </tbody>

</table>