config/routes.rb
Rails.application.routes.draw do

  root :to => 'seminars#index'

  get 'participants/future-faculty-program', to: 'participants/programs/future_faculty#index',
      format: 'xlsx', as: 'future_faculty_program_participants'

  resources :participants, except: :new, controller: "participants/base" do
    resource 'future-faculty-program',
             as: :future_faculty_program,
             controller: "participants/programs/future_faculty",
             only: [:enroll, :unenroll,
                    :graduate, :ungraduate,
                    :drop, :undrop, :reenroll] do
      member do
        patch 'enroll'
        patch 'unenroll'
        patch 'graduate'
        patch 'ungraduate'
        patch 'drop'
        patch 'undrop'
        patch 'reenroll'
      end
    end
    
    resource 'transcript', only: :show, controller: "participants/transcripts", format: 'pdf'

    scope shallow_prefix: "participant" do
      resources 'activities',
                only: [:edit, :create, :update, :destroy],
                controller: "participants/activities",
                shallow: true
     end
  end
  

  get 'transcript', to: 'participants/transcripts#show', format: 'pdf'

  patch 'admin/seminars/update_seminar' => 'admin/seminars#update_seminar', :as => 'update_whole_seminar'

  resources :seminars do
    resources :registrations, only: [:create, :destroy]
  end
  get 'registrations', to: 'registrations#index', :as => 'registrations'
  patch 'admin/seminars/mark_all_attended' => 'admin/seminars#mark_all_attended', :as => 'mark_all_attended_seminar'
  patch 'admin/seminars/mark_all_cleared' => 'admin/seminars#mark_all_cleared', :as => 'mark_all_cleared_seminar'
  
  patch 'admin/seminars/mark_attended' => 'admin/seminars#mark_attended', :as => 'mark_attended_seminar'
  

  resources :sessions, only: [:create, :destroy]
  get 'login',  to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', via: [:get, :delete]

  resource :search, only: :show

  get 'admin' => 'admin/seminars#index', :as => 'root_admin_url'
  namespace :admin do
    resources :seminars do
      resources :registrations
    end

    resources :spreadsheets, only: [:show]
    resources :settings, only: [:index, :update]
  end
  

end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-34625822-2', 'cmu.edu');
  ga('send', 'pageview');

</script>

app/views/layouts/_impersonate_user.html.erb
<div id="impersonate_participant">

    
    <p>Demo Helper</p>
    <div class="impersonate-widget">
      <ul>
        <li>
          <img alt="Face" src="/assets/face.png" /><%= link_to 'No One', impersonate_login_url('nobody') %>
          <p>Before login.</p>
        </li>

        <li>
          <img alt="Face" src="/assets/face.png" /><%= link_to 'Hilary Schuldt', impersonate_login_url('hilaryf') %>
          <p>A graduate student.</p>
        </li>

        <li>
          <img alt="Face" src="/assets/face.png" /><%= link_to 'Michelle Pierson', impersonate_login_url('mg2e') %>
          <p>An administrator.</p>
        </li>
    </div>
    <% if not session[:participant_id] %>
    <p>You are viewing this page as: No one logged in | <%= link_to "change", '#', :onclick => "switchUser()" %></p>
    <% else %>
    <p>You are viewing this page as: <%= current_user.name %> | <%= link_to "change", '#', :onclick => "switchUser()" %></p>
    <% end %>

    <script>
      function switchUser() {
        $('#impersonate_participant p a').attr( 'onclick', "cancelSwitch()" );
        $('#impersonate_participant p a').html('cancel');
        $('.impersonate-widget').slideDown();
      }
      function cancelSwitch() { 
        $('#impersonate_participant p a').attr( 'onclick', "switchUser()" );
        $('#impersonate_participant p a').html('change');
        $('.impersonate-widget').slideUp();
      }

    </script>    
  </div>

app/views/layouts/_page_footer.html.erb
<footer id="page-footer" role="contentinfo" class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <nav>
                <ul>
                    <li><%= link_to 'Eberly Center for Teaching Excellence', 'http://www.cmu.edu/teaching' %></li>
                    <li><%= link_to 'eberly-ctr@andrew.cmu.edu', 'mailto:eberly-ctr@andrew.cmu.edu?subject=Teaching%20Support%20Request' %></li>
                    <li><%= link_to '(412) 268-2896', 'tel:1-412-268-2896' %></li>
                </ul>
            </nav>
            <p>Our job is to help <em>you</em> be successful in your teaching</p>
        </div>
    </div>
</footer>

app/views/layouts/_page_header.html.erb
<header id="page-header" class="container-fluid">
    <div class="row">
        <div class="wordmark col-md-3">
            <%= link_to(
                        image_tag( 'eberly-wordmark.png',
                                  :alt => 'Eberly Wordmark'
                                  ),
                        "http://www.cmu.edu/teaching"
                        )
            %>
        </div>
        
        <div class="banner col-md-4">
            <h1><%= page_title %></h1>
        </div>
        
        <div class="header-content col-md-5 pull-right">
            <%= header_content %>
        </div>
    </div><!-- /.row -->
</header>

app/views/layouts/_search.html.erb
<%# TODO: Clean this up %>
<%= form_tag( search_url, :id => "site-search", :method => "get", class: "form-inline" ) do %>
    <div class="input-group">
        <%= text_field_tag(:search, "", { class: "form-control", placeholder: "Search for..." }) %>
        <span class="input-group-btn">
            <%= submit_tag("Go!", { class: "btn btn-default" } ) %>
        </span>
    </div>

<% end %>

app/views/layouts/_utility_nav.html.erb
<div id="navigation">
    <nav id="utility-nav">
        <h1>Welcome!</h1>
        <ul>
            <% if authenticated? %>
                <li class="name"><%= current_user.name %></li>
                <li class="logout"><%= link_to "Logout", logout_url %></li>
                
            <% else %>
                <li class="login"><%= link_to content_tag(:span, 'Login', :class => 'capitalize') + ' to sign up', login_url %></li>
                
            <% end %>
        </ul>
    </nav>
    
    <% if administrator? %>
        <nav id="admin-nav">

            <div class="row">
                <div class="col-md-12">
                    <div class="btn-group">
                        <%= link_to raw('<span class="glyphicon glyphicon-plus"></span><span class="sr-only">Create New Seminar</span>'), new_admin_seminar_url, { class: "btn btn-create" } %>
                        <%= link_to "Create New Seminar", new_admin_seminar_url, { class: "btn btn-create" } %>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <ul>  
                        <li><%= link_to "Seminars > all", admin_seminars_url %></li>
                        <li><%= link_to "Seminars > published", admin_seminars_url( :status => 'published' ) %></li>
                        <li><%= link_to "Seminars > drafts", admin_seminars_url( :status => 'drafts' ) %></li>
                        
                        <li><%= link_to "List details > seminars", admin_spreadsheet_url( :id => 'seminars' ) %></li>
                        <li><%= link_to "List details > people", admin_spreadsheet_url( :id => 'participants') %></li>
                        
                        <li><%= link_to "Application Settings", admin_settings_url %></li>
                    </ul>
                </div>
            </div>
        </nav>

<% elsif authenticated? %>
  <nav id="site-nav">
    <ul>
      <li class="primary<% if params[:controller] == 'seminars' %> active<% end %>">
        <%= link_to "Teaching Seminars Listing", registrations_url %>
      </li>
      <li class="primary">
	<%= link_to "Confirmed Seminars [.ics]", registrations_path( :format => :ics ) %>
	<%= image_tag "calendar-icon.png", :alt => "Calendar" %>
      </li>

      <li><%= link_to "Future Faculty Program", "http://www.cmu.edu/teaching/graduatestudentsupport/documentationofteaching.html" %></li>
      <li<% if params[:controller] == 'transcript' %> class="active"<% end %>><%= link_to "My Eberly Transcript", transcript_url %></li>
    </ul>
  </nav>

<% end %>
</div>

app/views/layouts/_welcome_message.html.erb
<p id="welcome-message">
  Every semester, Eberly Center offers a series of
  <strong>seminars covering various teaching topics.</strong>
  Each seminar is two hours long and are <strong>free</strong> to
  all PhD, master, and post-doc students.
</p>

app/views/layouts/admin.html.erb
<% content_for :stylesheets do %>
  <%#= stylesheet_link_tag "admin/", :media => "all" %>
<% end %>

<%= render :template => 'layouts/application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= document_title %></title>

  <%= stylesheet_link_tag 'application', :media => "all" %>
  
  <% if content_for :stylesheets %>
    <%= yield :stylesheets %>
  <% end %>

  <%= javascript_include_tag 'application' %>
  <%= render partial: 'layouts/analytics' %>

  <%= csrf_meta_tags %>
</head>
<body>
  <script type="text/javascript">
  var default_filter="<%= @display_tag %>";
  </script>

  <%#= render :partial => "layouts/impersonate_user" %>

  <div id="cmu-bar-container" class="container-fluid">
    <div id="cmu-bar">
      <%= link_to( image_tag( 'carnegie-mellon-wordmark.gif', 
                   :alt => 'Carnegie Mellon Wordmark'),
                   'http://www.cmu.edu' )
      %>
    </div>
  </div>

  <%= render partial: 'layouts/page_header' %>

  <div class="container-fluid">
      <div class="row">
          <div class="col-md-3 sidebar">
              <%= render "layouts/utility_nav" %>
              
              <%= sidebar_note %>
          </div>

          <div class="col-md-9">
              <div class="row">
                  <div class="col-md-12">
                      <%# TODO: raw is cludgy and requires no direct user input to go in the flash.
                      Let's whitelist some reasonable tags instead %>
                      <% if flash[:error] %><div class="flash error"><p><%= raw flash[:error] %></p></div><% end %>
                      <% if flash[:notice] %><div class="flash notice"><p><%= raw flash[:notice] %></p></div><% end %>
                      <% if flash[:success] %><div class="flash success"><p><%= raw flash[:success] %></p></div><% end %>
                  </div>
              </div>

              <div class="row">
                  <section id="content" role="main" class="col-md-12">
                      <%= yield %>
                  </section>
              </div>
          </div><!-- /.col-md-9 -->
      </div><!-- /.row -->
  </div>

  <%= render partial: 'layouts/page_footer' %>

</body>
</html>